using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TelehealthBooking.Domain.Entities;

namespace TelehealthBooking.Infrastructure.Persistence.Configurations;

public class AppointmentConfiguration : IEntityTypeConfiguration<Appointment>
{
    public void Configure(EntityTypeBuilder<Appointment> builder)
    {
        // Set the Primary Key
        builder.HasKey(a => a.Id);

        // Enforce database-level constraints
        builder.Property(a => a.Status)
               .HasMaxLength(50)
               .IsRequired();

        builder.Property(a => a.CancellationReason)
               .HasMaxLength(500);

        // This ensures the ID isn't auto-generated by SQL since we generate Guids in the Domain
        builder.Property(a => a.Id).ValueGeneratedNever();
    }
}